### ISSUE TITLE
Running through grah a second time

### ISSUE THREAD

**Issue by SimonDeKeyser** [learningmatter-mit/Atomistic-Adversarial-Attacks#1]
When trying to perform an adversarial attack with my model, i got the error:

"RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed"

Could this be because the forces are calculated inside of the model, which means that the backward gradients are being computed? I follow your code, but the only difference is that I do not use a NeuralFF model from your NFF github.

Did you have any issues while implementing this which could help me?
Thank you

**Comment by dskoda** [comment]
I believe this is related to the flag `retain_graph=True` after obtaining the forces from the gradients. The forces in NFF are calculated passing this flag to `torch.autograd.grad` (see [this line](https://github.com/learningmatter-mit/NeuralForceField/blob/master/nff/utils/scatter.py#L24)). If the flag is set to `False` (default), the computational graph is freed [according to the docs](https://pytorch.org/docs/stable/generated/torch.autograd.grad.html), which seems to be your issue. Check if you're retaining the computational graph in your model when calculating the forces - hope it helps.

**Comment by SimonDeKeyser** [comment]
That did it! Thank you
